### PR TITLE
New icons #83

### LINKED ISSUE #83: Nodes Icons
Hi, 
I can help to put an icon for each node (reuse existing one from freecad or create a new one) let me know if this is needed.

I am an advanced user of Solidworks and Grasshopper so I following this Addon with a lot of hope. 
I am not a programmer but I would like to help.

Thanks.

### PR DESCRIPTION
**Pull request by Emilien-Etadam**
YFnBRf3nK9

Fixes #83

### CODE REVIEW

**Comment by j8sr0230** [comment]
Thanks for the great new icons. Could you scale them to 32x32 pixel next time?

**Comment by Emilien-Etadam** [comment]
Ok I don't really know how to manage the sizes when I export to svg but I will pay attention to this.

**Comment by j8sr0230** [comment]
Otherwise huge icons appear during node dragging :)

nodes_dragging_icon_issues

**Comment by Emilien-Etadam** [comment]
OK let me check

**Pull request merged**
